release version 2.0.4
nasa/cumulus-message-adapter pull request #111
Opened 2024-08-13 15:25 UTC by etcart

update version and release

2024-10-02 17:10 UTC, npauzenga requested changes

2025-03-06 17:54 UTC, etcart commented on .circleci/config.yml
> +            yum update -y && yum install -y zip openssh-clients git curl make jq binutils
it causes it to work:
yum update will ask "are you sure"? and you have to hit yes, or this flag says "auto-yes"

2025-03-06 17:58 UTC, etcart commented on .circleci/config.yml
> -          filters:
these needed to be set back on, turned off to allow for debugging

2025-03-06 21:12 UTC, charleshuang80 approved these changes

2025-03-12 16:11 UTC, npauzenga approved these changes

2025-03-12 16:49 UTC, merged